import type { Project } from '../types';
import project5 from '../assets/project5.png';
import project1 from '../assets/project1.png';
export const projects: Project[] = [
    {
        id: 'case1',
        caseLabel: 'Project 1',
        title: 'E-Commerce and Affiliate Website | PT Bizhub Digital Indonesia',
        description: 'An e-commerce website with an affiliate system, personally owned by PT Bizhub Digital Indonesia.',
        tags: ['React.js', 'Vite', 'Typescript'],
        thumbnail: project1,
        liveUrl: 'https://bizhub-frontend.onrender.com/',
        codeUrl: ' ',
    },
    {
        id: 'case2',
        caseLabel: 'Project 2',
        title: 'Renting System for Badminton Court',
        description: 'A booking and rental system for badminton courts.',
        tags: ['Express.js', 'PRISMA'],
        thumbnail: '',
        liveUrl: ' ',
        codeUrl: 'https://github.com/Yow04/renting-api',
    },
    {
        id: 'case3',
        caseLabel: 'Project 3',
        title: 'AI-Fish Disease Detector Mobile Apps',
        description: 'A mobile application to detect fish diseases using AI-powered image recognition.',
        tags: ['Kotlin', 'Android'],
        thumbnail: '',
        liveUrl: ' ',
        codeUrl: 'https://github.com/SandyAryadika/Ifishy-C242-PS164',
    },
    {
        id: 'case4',
        caseLabel: 'Project 4',
        title: 'Bizhub Management Task',
        description: 'A task management application built as the final project for a project management course.',
        tags: ['Typescript'],
        thumbnail: '',
        liveUrl: 'https://manatask-bzhb.netlify.app/',
        codeUrl: 'https://github.com/Yow04/bizhub-management-task',
    },
    {
        id: 'case5',
        caseLabel: 'Project 5',
        title: 'Know Your Tea Website',
        description: 'A website for detecting tea plant diseases through leaf image analysis.',
        tags: ['React', 'Python', 'Ngrok'],
        thumbnail: project5,
        liveUrl: 'https://tea-bug.vercel.app/',
        codeUrl: 'https://github.com/Yow04/know-your-tea',
    },
];