import type { Project } from '../types';
import project5 from '../assets/project5.png';
import project1 from '../assets/project1.png';
export const projects: Project[] = [
    {
        id: 'case1',
        caseLabel: 'Proyek Nomor 1',
        title: 'E-Commerce and Affiliate Website | PT Bizhub Digital Indonesia',
        description: 'Sebuah website e-commerce serta sistem afiliasi yang dimiliki secara personal oleh PT Bizhub Digital Indonesia',
        tags: ['React.js', 'Vite', 'Typescript'],
        thumbnail: project1,
        liveUrl: 'https://bizhub-frontend.onrender.com/',
        codeUrl: ' ',
    },
    {
        id: 'case2',
        caseLabel: 'Proyek Nomor 2',
        title: 'Renting System for Badminton Court',
        description: 'Sebuah sistem untuk pemesanan lapangan badminton',
        tags: ['Express.js', 'PRISMA'],
        thumbnail: '/projects/project2.png',
        liveUrl: ' ',
        codeUrl: 'https://github.com/Yow04/renting-api',
    },
    {
        id: 'case3',
        caseLabel: 'Proyek Nomor 3',
        title: 'AI-Fish Disease Detector Mobile Apps',
        description: 'Membuat sebuah aplikasi mobile untuk mendeteksi penyakit dari ikan',
        tags: ['Kotlin', 'Android'],
        thumbnail: '/projects/project3.png',
        liveUrl: ' ',
        codeUrl: 'https://github.com/SandyAryadika/Ifishy-C242-PS164',
    },
    {
        id: 'case4',
        caseLabel: 'Proyek Nomor 4',
        title: 'Bizhub Management Task',
        description: 'Membuat sebuah aplikasi sebagai hasil akhir dari mata kuliah manajemen proyek.',
        tags: ['Typescript'],
        thumbnail: '/projects/project4.png',
        liveUrl: 'https://manatask-bzhb.netlify.app/',
        codeUrl: 'https://github.com/Yow04/bizhub-management-task',
    },
    {
        id: 'case5',
        caseLabel: 'Proyek Nomor 5',
        title: 'Know Your Tea Website',
        description: 'Membuat sebuah website deteksi penyakit tanaman teh melalui media citra pada bagian daun.',
        tags: ['React', 'Python', 'Ngrok'],
        thumbnail: project5,
        liveUrl: 'https://tea-bug.vercel.app/',
        codeUrl: 'https://github.com/Yow04/know-your-tea',
    },
];